[channels.stable.plugins.ActionTimeline]
built_commit = "9c3df56537445f62a6bd3bd205f195eea739ea61"
time_built = 2024-04-15T16:23:36.944
effective_version = "1.3.0.1"
[channels.stable.plugins.ActionTimeline.changelogs."1.3.0.1"]
time_released = 2024-04-15T16:23:36.944
changelog = "Update for KR"
[channels.stable.plugins.Accountant]
built_commit = "4ddf9fbf2081c2a412fb93b4a27bc51ab2ee72bb"
time_built = 2024-05-09T17:48:57.550
effective_version = "1.4.0.0"
[channels.stable.plugins.Accountant.changelogs]
[channels.testing-live.plugins.Umbra]
built_commit = "f583e15145e7496be6aba318107077df775092d1"
time_built = 2024-05-09T11:43:57.892
effective_version = "1.0.6.10"
[channels.testing-live.plugins.Umbra.changelogs."1.0.2.18"]
time_released = 2024-04-30T10:22:54.295
changelog = " - Fixed an error that would occur when placing a flag marker in an area without an Aetheryte.\n - Fixed the master volume value not displayed correctly in the volume widget.\n - Umbra will now use custom icons if they are available.\n - Add an option to disable image processing for some icons under General Settings.\n"
[channels.testing-live.plugins.Umbra.changelogs."1.0.3.1"]
time_released = 2024-05-06T06:03:59.529
changelog = " - Fixed the settings window from rebinding events more than once.\n"
[channels.testing-live.plugins.Umbra.changelogs."1.0.4.5"]
time_released = 2024-05-06T06:16:30.300
changelog = " - Fixed the settings window from rebinding events more than once.\n"
[channels.testing-live.plugins.Umbra.changelogs."1.0.6.10"]
time_released = 2024-05-09T11:43:57.892
changelog = " - Fixed the settings window from rebinding events more than once.\n"
[channels.testing-net6.plugins]
